spring:
  application:
    name: StoreManagement
  datasource:
    url: jdbc:sqlite:store.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: com.storemanagement.config.SQLiteDialect
    show-sql: true
  sql:
    init:
      mode:
        never